modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${ext.mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/KuryKat-Modpacks/${mod_id}/${minecraft_version}${ext.isRelease.toBoolean() ? '/release' : '/dev' }/updates.json"
displayURL="${mod_homepage}"
logoFile="${mod_id}_banner.png"
logoBlur=false
authors="${mod_author}"
displayTest="MATCH_VERSION"
itemIcon="${mod_id}:ruby"

description='''

${mod_description}

'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="configured"
mandatory=false
versionRange="[${configured_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="catalogue"
mandatory=false
versionRange="[${catalogue_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"

[modproperties.${mod_id}]
catalogueImageIcon="${mod_id}_icon.png"
catalogueBackground="${mod_id}_background.png"
configuredBackground="minecraft:textures/block/polished_andesite.png"