name: Increment Build Number

on:
  push:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+/dev"
jobs:
  increment-build-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}

      - name: Increment Build Number
        run: |
          property_value=$(grep '^mod_build_numbers=' gradle.properties | cut -d'=' -f2)
          incremented_value=$((property_value + 1))
          sed -i "s/^mod_build_numbers=.*/mod_build_numbers=$incremented_value/" gradle.properties

      - name: Commit Changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an gradle.properties)"
          git config user.email "$(git log -n 1 --pretty=format:%ae gradle.properties)"
          
          git pull
          git diff --exit-code gradle.properties || (git add gradle.properties && git commit -m "👷 Chore: Bump Build Numbers")
          git push
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
